channels:
  - conda-forge
  - defaults
  - districtalab
dependencies:
  - bokeh >= 2.2
  - cartopy >= 0.18
  - colorcet >= 2.0
  - contextily >= 1.0
  - cookiecutter
  - dask >= 2.27
  - datashader >= 0.11
  - descartes >= 1.1
  - fastparquet >= 4.1
  - fiona >= 1.8
  - folium >= 0.11
  - geoalchemy2 >= 0.6
  - geocube
  - geopandas >= 0.8.1
  - geopy >= 2.0
  - georasters
  - geos >= 3.8.1
  - geoviews >= 1.8
  - holoviews >= 1.13
  - hvplot >= 0.6
  - ipykernel >= 5.3
  - ipython >= 7.18
  - ipywidgets >= 7.5
  - jupyter >= 1.0.0
  - jupyterlab >= 2.2.8
  - matplotlib >= 3.3.2
  - nodejs
  - numpy >= 1.19
  - pandas >= 1.1
  - pyarrow
  - pygeos
  - python >= 3.8
  - rasterio >= 1.1.6
  - rasterstats >= 0.14
  - rioxarray
  - scikit-learn >= 0.23
  - scipy >= 1.3
  - seaborn >= 0.11
  - shapely >= 1.7
  - snappy
  - spatialpandas >= 0.3.6
  - sqlalchemy >= 1.3
  - statsmodels
  - tqdm
  - xarray-spatial
  - yellowbricks